#!/bin/bash

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
IS_USB=/usr/share/calamares/helpers/calamares-bootloader-config-root-on-usb.py

echo "Running bootloader-config..."

if python3 $IS_USB $CHROOT; then
    # Install grub2-fll-portable-efi in the chroot
    APTSOURCES=$(mktemp -d --tmpdir=${CHROOT}/tmp/ liveapt.XXXXXX)
    APTGETBASE="apt-get -o Dir::Etc=${APTSOURCES##${CHROOT}}"
    . /lib/init/fll
    APTMOUNT="/fll"
    [ -e "${APTMOUNT}/extras" ] || APTMOUNT="$(fll_get_mnt)"
    mount -o bind ${APTMOUNT} ${CHROOT}/mnt
    echo 'deb [trusted=yes] file:///mnt/extras sid main' > \
        ${APTSOURCES}/sources.list
    mkdir ${APTSOURCES}/preferences.d
    chroot $CHROOT ${APTGETBASE} update > /dev/null
    DEBIAN_FRONTEND=noninteractive chroot $CHROOT ${APTGETBASE} \
        --allow-unauthenticated --assume-yes \
        install grub2-fll-portable-efi os-prober-
    umount ${CHROOT}/mnt
    echo '' > ${APTSOURCES}/sources.list
    chroot $CHROOT ${APTGETBASE} update > /dev/null
    chroot $CHROOT ${APTGETBASE} clean > /dev/null
    rm -rf ${APTSOURCES}
    # disable os-prober to be sure
    if grep -q '^#GRUB_DISABLE_OS_PROBER' $CHROOT/etc/default/grub; then
        sed -i "s/#GRUB_DISABLE_OS_PROBER=false/\nGRUB_DISABLE_OS_PROBER=true/g" \
            $CHROOT/etc/default/grub
    elif grep -qv '^GRUB_DISABLE_OS_PROBER' $CHROOT/etc/default/grub; then
        printf "\nGRUB_DISABLE_OS_PROBER=true\n" >>$CHROOT/etc/default/grub
    fi
else
    # enable os-prober
    if grep -q '^#GRUB_DISABLE_OS_PROBER' $CHROOT/etc/default/grub; then
        sed -i "s/#GRUB_DISABLE_OS_PROBER=false/\nGRUB_DISABLE_OS_PROBER=false/g" \
            $CHROOT/etc/default/grub
    elif grep -qv '^GRUB_DISABLE_OS_PROBER' $CHROOT/etc/default/grub; then
        printf "\nGRUB_DISABLE_OS_PROBER=false\n" >>$CHROOT/etc/default/grub
    fi
fi

# enable a grub theme, if it exists
. /etc/default/distro
if [ -n "${FLL_GFXBOOT_THEME}" ] && \
   [ -r "/usr/share/grub/themes/${FLL_GFXBOOT_THEME}/theme.txt" ]; then
    if grep -q ^GRUB_THEME\= "${CHROOT}/etc/default/grub" >/dev/null 2>&1; then
            sed -i "s|\(GRUB_THEME=\).*|\1/usr/share/grub/themes/${FLL_GFXBOOT_THEME}/theme.txt|" \
                "${CHROOT}/etc/default/grub"
    else
        printf "\nGRUB_THEME=\"/usr/share/grub/themes/${FLL_GFXBOOT_THEME}/theme.txt\"\n" \
            >>"${CHROOT}/etc/default/grub"
    fi
fi
