#!/bin/bash

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
ON_USB=/usr/share/calamares/helpers/calamares-bootloader-config-chroot-on-usb.py

echo "Running bootloader-config..."

if python3 $ON_USB $CHROOT; then
    # Install grub2-fll-portable-efi in the chroot
    mount -o bind /fll ${CHROOT}/fll
    APTGETBASE=$(find /fll/apt -type f -name '*.deb' | \
        awk 'BEGIN{ print "apt-get -y \\"} { print "\t--with-source", $1, " \\"} END { print "\tinstall"}')
    DEBIAN_FRONTEND=noninteractive chroot $CHROOT ${APTGETBASE} grub2-fll-portable-efi os-prober-
    umount ${CHROOT}/fll
    # disable os-prober to be sure
    if grep -q '^#GRUB_DISABLE_OS_PROBER' $CHROOT/etc/default/grub; then
        sed -i "s/#GRUB_DISABLE_OS_PROBER=false/\nGRUB_DISABLE_OS_PROBER=true/g" \
            $CHROOT/etc/default/grub
    elif grep -qv '^GRUB_DISABLE_OS_PROBER' $CHROOT/etc/default/grub; then
        printf "\n# Disable other OS discovery\n" >>$CHROOT/etc/default/grub
        printf "GRUB_DISABLE_OS_PROBER=true\n" >>$CHROOT/etc/default/grub
    fi
else
    # enable os-prober
    if grep -q '^#GRUB_DISABLE_OS_PROBER' $CHROOT/etc/default/grub; then
        sed -i "s/#GRUB_DISABLE_OS_PROBER=false/GRUB_DISABLE_OS_PROBER=false/g" \
            $CHROOT/etc/default/grub
    elif grep -qv '^GRUB_DISABLE_OS_PROBER' $CHROOT/etc/default/grub; then
        printf "\n# Enable other OS discovery\n" >>$CHROOT/etc/default/grub
        printf "GRUB_DISABLE_OS_PROBER=false\n" >>$CHROOT/etc/default/grub
    fi
fi
