#!/bin/sh

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

. /etc/default/distro
. /usr/lib/init/fll

# fix sudo config
rm "${CHROOT}/etc/sudoers.d/15_${FLL_DISTRO_NAME}"
cat "${CHROOT}/usr/share/base-files/profile" > "${CHROOT}/etc/profile"

# regenerate default snakeoil with new hostname
if which make-ssl-cert >/dev/null; then
    chroot $CHROOT make-ssl-cert generate-default-snakeoil --force-overwrite
fi

# "normalize" gettys
rm -f	"${CHROOT}/etc/systemd/system/getty@.service" \
    "${CHROOT}/etc/systemd/system/autovt@.service"
ln -fs	/lib/systemd/system/autovt@.service \
    "${CHROOT}/etc/systemd/system/getty.target.wants/getty@tty1.service"

# normalize /etc/pam.d/login
sed -i '/^#.*pam_lastlog\.so/s/^#[ \t]\+//' "${CHROOT}/etc/pam.d/login"

# remove confusing live traces from blkid.tab
rm -f "${CHROOT}/etc/blkid.tab*"

# install the same package set as if liveapt ran at boot
mkdir -p "${CHROOT}/fll"
mount --bind /fll "${CHROOT}/fll"
chroot $CHROOT /usr/share/fll-live-initscripts/fll_locales localize
umount "${CHROOT}/fll"

# remove /fll
rm -rf "${CHROOT}/fll"

# remove /etc/default/distro
rm -f /etc/default/distro

exit 0
