#!/bin/bash

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

echo "Running cryptsetup-purge..."

# Set secure permissions for the initramfs if we're configuring full-disk-encryption.
if [ "$(mount | grep $CHROOT" " | cut -c -16)" = "/dev/mapper/luks" ]; then
    echo "UMASK=0077" > $CHROOT/etc/initramfs-tools/conf.d/initramfs-permissions
else
    DEBIAN_FRONTEND=noninteractive chroot $CHROOT dpkg --purge \
        cryptsetup-initramfs cryptsetup keyutils
fi
