#!/bin/sh

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

. /etc/default/distro

# regenerate default snakeoil with new hostname
if which make-ssl-cert >/dev/null; then
    chroot $CHROOT make-ssl-cert generate-default-snakeoil --force-overwrite
fi

# install the same package set as if liveapt ran at boot
mkdir -p "${CHROOT}/fll"
mount --bind /fll "${CHROOT}/fll"
chroot $CHROOT /usr/share/fll-live-initscripts/fll_locales localize
umount "${CHROOT}/fll"
rm -rf "${CHROOT}/fll"

# remove /etc/default/distro
rm -f "${CHROOT}/etc/default/distro"

exit 0
