#!/bin/sh
# Creates an "Install Debian" icon on the live session tested with:
# Xfce, LXDE, LXqt, Gnome, KDE, Mate, Cinnamon

# We query xdg-user-dir because the Desktop directory has different
# names for different languages
DESKTOP=$(xdg-user-dir DESKTOP)

# Create ~/Desktop just in case this runs before the xdg folder
# creation script.
mkdir -p $DESKTOP

# Among the Debian desktop environments, LXDE is the only one
# that behaves completely different.
if [ -f /usr/bin/lxsession ]; then
    echo "[Desktop Entry]" > $DESKTOP/calamares-install-aptosid.desktop
    echo "Type=Link" >> $DESKTOP/calamares-install-aptosid.desktop
    echo "Name=Install aptosid" >> $DESKTOP/calamares-install-aptosid.desktop
    echo "Icon=install-aptosid" >> $DESKTOP/calamares-install-aptosid.desktop
    echo "URL=/usr/share/applications/calamares-install-aptosid.desktop" \
          >> $DESKTOP/calamares-install-aptosid.desktop
else
    cp /usr/share/applications/calamares-install-aptosid.desktop $DESKTOP
    # Xfce needs this executable otherwise it complains, everything
    # else doesn't seem to care either way.
    chmod +x $DESKTOP/calamares-install-aptosid.desktop
fi

# Set desktop launcher as trusted under Xfce (See: #1037299)
if [ "$XDG_CURRENT_DESKTOP" = "XFCE" ]; then
    gio set --type=string ~/Desktop/calamares-install-aptosid.desktop \
        metadata::trusted true
    gio set --type=string ~/Desktop/calamares-install-aptosid.desktop \
        metadata::xfce-exe-checksum \
        "$(sha256sum ~/Desktop/calamares-install-aptosid.desktop | cut -f1 -d' ')"
    touch ~/Desktop/calamares-install-aptosid.desktop
fi

# Preload calamares binaries and libraries using idle disk cycles
# so that it launches faster
ionice -C Idle cat /usr/bin/calamares > /dev/null
for file in $(ldd /usr/bin/calamares | awk '{print $3}'); do
    ionice -C Idle cat $file > /dev/null
done

# create aptosid icons
if [ -s /etc/default/distro ]; then
    . /etc/default/distro

    if [ ! -f "$DESKTOP/aptosid-manual.desktop" ] && \
    [ -f /usr/share/applications/aptosid/aptosid-manual.desktop ]; then
        install -o ${FLL_LIVE_USER} -g ${FLL_LIVE_USER} -m 0755 \
            /usr/share/applications/aptosid/aptosid-manual.desktop
            "$DESKTOP/"
    fi

    if [ ! -f "$DESKTOP/aptosid-irc.desktop" ] && \
    [ -f /usr/share/applications/aptosid/aptosid-irc.desktop ]; then
        install -o ${FLL_LIVE_USER} -g ${FLL_LIVE_USER} -m 0755 \
            /usr/share/applications/aptosid/aptosid-irc.desktop \
            "$DESKTOP/"
    fi

    # scan for index.html in fll specific live mountpoint directories
    for mntpnt in /fll/*; do
        if [ -d "${mntpnt}" ] && [ -f "${mntpnt}/index.html" ]; then
            INDEXFILE="${mntpnt}/index.html"
            for ext in svg png gif ico; do
                if [ -f "${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}" ]; then
                    INDEXICON="${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}"
                    break
                fi
            done
            break
        fi
    done

    ###
    # create desktop shortcut to index.html
    ###
    if [ -f "${INDEXFILE}" ] && [ ! -f "$DESKTOP/${FLL_DISTRO_NAME}.desktop" ]; then
        cat > "$DESKTOP/${FLL_DISTRO_NAME}.desktop" \
    <<EOF
#!/usr/bin/env xdg-open
[Desktop Entry]
Encoding=UTF-8
Type=Application
Exec=x-www-browser file://${INDEXFILE}
Icon=${INDEXICON}
Terminal=false

Name=${FLL_CDROM_INDEX}
GenericName=${FLL_CDROM_INDEX}
EOF
        chmod u+x "$DESKTOP/${FLL_DISTRO_NAME}.desktop"
    fi
fi
