#!/bin/sh
###
# Wrapper for running calamares on aptosid live media
###

. /etc/default/distro
. /usr/lib/init/fll
pkexec ln -sf "$(fll_get_mnt)/${FLL_IMAGE_LOCATION}" /fll/squashfs
if [ ! -f /fll/squashfs ] && [ -L /dev/fll ]; then
    pkexec ln -sf /dev/fll /fll/squashfs
fi

if [ ! -f /fll/squashfs ]; then
    echo "$0: failed to create /fll/squashfs symlink"
fi

# Stale file left behind by live-build that messes with partitioning
if [ -e /etc/fstab ]; then
    pkexec mv /etc/fstab /etc/fstab.orig.calamares
fi

# Access control to run calamares as root for xwayland
xhost +si:localuser:root
pkexec calamares
xhost -si:localuser:root

# Restore stale fstab, for what it's worth
if [ -e /etc/fstab.orig.calamares ]; then
    pkexec mv /etc/fstab.orig.calamares /etc/fstab
fi
