#!/bin/sh
###
# Wrapper for running calamares on aptosid live media
###

if [ -L /dev/fll ]; then
    sudo ln -sf /dev/fll /fll/squashfs
else
    . /etc/default/distro
    sudo ln -sf /fll/*/${FLL_IMAGE_LOCATION} /fll/squashfs
fi

# Stale file left behind by live-build that messes with partitioning
sudo mv /etc/fstab /etc/fstab.orig.calamares

# Access control to run calamares as root for xwayland
xhost +si:localuser:root
sudo calamares
xhost -si:localuser:root

# Restore stale fstab, for what it's worth
sudo mv /etc/fstab.orig.calamares /etc/fstab
