#!/bin/sh

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

. /etc/default/distro

# During live boot an unfixated home was blessed, and the calamares users
# module was disabled via settings.conf. This means a local block device was
# present matching the systemd-homed key pair included on the live media.
# Pass this identity into the installed system.
if [ -r "/var/lib/systemd/home/${FLL_LIVE_USER}.identity" ]; then
    cp --archive "/var/lib/systemd/home/${FLL_LIVE_USER}.identity" \
        "${CHROOT}/var/lib/systemd/home/${FLL_LIVE_USER}.identity"
    if [ -d "/var/cache/systemd/home/${FLL_LIVE_USER}" ]; then
        cp --archive --recursive "/var/cache/systemd/home/${FLL_LIVE_USER}" \
            "${CHROOT}/var/cache/systemd/home/${FLL_LIVE_USER}"
    fi
fi

# regenerate default snakeoil with new hostname
if which make-ssl-cert >/dev/null; then
    chroot $CHROOT make-ssl-cert generate-default-snakeoil --force-overwrite
fi

if which sshd >/dev/null; then
    # create openssh keys for new host
    chroot $CHROOT dpkg-reconfigure --frontend=noninteractive openssh-server
fi

if ! systemd-detect-virt --quiet; then
    DEBIAN_FRONTEND=noninteractive chroot $CHROOT dpkg --purge spice-vdagent qemu-guest-agent
fi

# set up root shell
cat << EOF > "${CHROOT}/root/.bashrc"
. /etc/profile
EOF

# Setup console and keyboard defaults to match live session
chroot $CHROOT /usr/share/fll-live-initscripts/fll_locales localize

# remove /etc/default/distro
rm -f "${CHROOT}/etc/default/distro"

exit 0
