#!/bin/sh
set -e

case "$1" in
    remove)
        dpkg-divert --quiet --package calamares-settings-aptosid \
            --rename --remove /usr/share/applications/calamares.desktop
    ;;
esac

#DEBHELPER#
